### ISSUE TITLE
mail buffers, with orgalist-mode, prefix is not considered when virtual-fill is on

### ISSUE THREAD

**Issue by ouboub** [luisgerhorst/virtual-auto-fill#2]
Hi

First for all thanks for nice package, this is much more useful for me than visual-line-mode, especially in org buffers. It is even quite useful in mails, however there are two issues: a minor one considers the address fields such as CC, these are sometimes strangely displayed when virtual-fill-mode is on. The second one concerns the use of orgalist-mode in mail buffers. This mode allows to have (enumerated) lists. When I turn virtual-auto-fill-mode off and auto-fill-mode on, the lists are nicely filled as:

1. The first item blab bladnka bladnfkand adnfkaj kjkajdkfj ablkadf kj
   kajldjf adfkjaksdfjl  

While with auto-fill-mode off and visual-auto-fill-mode on the are displayed as

1. The first item blab bladnka bladnfkand adnfkaj kjkajdkfj ablkadf 
kj kajldjf adfkjaksdfjl

So the prefix is not taken into account. Is there any change to add such a feature?

regards

Uwe Brauer

**Comment by luisgerhorst** [comment]
Thanks for your report, here are my remarks:
- Regarding 1: Can you check if the issue is also reproducible using one/multiple individual packages used under the hood, in particular adaptive-wrap or visual-fill-column?
- Regarding 2: This is a bug, is the problem also present if you only enable adaptive-wrap and make your window very narrow?

If the problem persists with only those modes enabled, consider reporting / sending patches there. An example of the CC fields that are not displayed correctly would be great.

**Comment by ouboub** [comment]
>>> "LG" == Luis Gerhorst ***@***.***> writes:

Sorry for the delay
> Thanks for your report, here are my remarks:
> - Regarding 1: Can you check if the issue is also reproducible using
> one/multiple individual packages used under the hood, in particular
> adaptive-wrap or visual-fill-column?

1. If I use visual-fill-column I have the same problem.

2. Adaptive-wrap? Do you mean adaptive-wrap-prefix-mode? That does *not* cause any problems

> - Regarding 2: This is a bug, is the problem also present if you only enable adaptive-wrap and make your window very narrow?

Again adaptive-wrap-prefix-mode? That does *no* cause the problem. 
Also here the problem is caused by visual-fill-column


I have a thinkpad X1 14 inch Laptop and the windows is *not* very
narrow. So the culprit is visual-fill-column, at least

> If the problem persists with only those modes enabled, consider
> reporting / sending patches there. An example of the CC fields that
> are not displayed correctly would be great.

Do you mean a screenshot?

Regards

Uwe Brauer

**Comment by ouboub** [comment]
I just saw this on the org-mailing list by a lead developer

Nicolas Goaziou ***@***.***>

,----
|
| > So the prefix is not taken into account. Anybody seeing this and knows
| > a solution?
|
| Orgalist mode does not handle virtual indentation. Patches welcome,
| however.
`----

So I will close that bug, sorry for the noise.
